baseURL = "https://sharathp.github.io/"
enableInlineCSS = false
languageCode = "en-us"
title = "Sharath.P - Professional Resume"
theme = ""

[params]
  email = "sharathp22@gmail.com"
  phone = "+91 9743237944"
  location = "India, IN"
  github = "sharathp"
  linkedin = "http://www.linkedin.com/in/sharathp22"